Add celery tasks to update db
epedzich/cinema-city-clone pull request #5
Opened 2019-08-01 10:17 UTC by epedzich

2019-08-01 10:25 UTC, lukasz-michalak requested changes

2019-08-01 10:25 UTC, lukasz-michalak commented on cinemas_repertoire/tasks.py
> +        'schedule': crontab(minute=0, hour=0)
I would make schedule configurable via django settings

2019-08-01 10:25 UTC, lukasz-michalak commented on cinemas_repertoire/tasks.py
> +    for cinema in get_cinemas().values():
there is no guarantee that previous `update_cinemas.delay()` will be done/ready at this point. so it is quite possible you will be updating yesterdays data.

2019-08-01 13:23 UTC, epedzich commented on cinemas_repertoire/tasks.py
> +        'schedule': crontab(minute=0, hour=0)
Somethng like: <NAME_OF_TASK>_CRON = crontab(minute=0, hour=0)?

2019-08-01 14:01 UTC, lukasz-michalak commented on cinemas_repertoire/tasks.py
> +        'schedule': crontab(minute=0, hour=0)
tak, coś tego typu

2019-08-06 11:27 UTC, lukasz-michalak approved these changes

2019-08-06 11:55 UTC, merged